http {
server {
    listen 8080;
    root /home/lenovo/Desktop/Webserv/configs/location/www;

    location / {
        root /home/lenovo/Desktop/Webserv/configs/location/www;
        index index.html;
        allowed_methods GET;
    }
}
}
