http {
server {
    listen 8080;
    root /home/lenovo/Desktop/Webserv/configs/client_max_body_size/www;
    client_max_body_size 100k;

    location / {
        root /home/lenovo/Desktop/Webserv/configs/client_max_body_size/www;
        index index.html;
        allowed_methods GET;
    }

    location /upload {
        root /home/lenovo/Desktop/Webserv/configs/client_max_body_size/www;
        allowed_methods POST;
        upload_location /home/lenovo/Desktop/Webserv/configs/client_max_body_size/uploads;
    }
}
}
