http {
server {
    listen 8080;
    root /home/lenovo/Desktop/Webserv/configs/autoindex/www;

    location / {
        root /home/lenovo/Desktop/Webserv/configs/autoindex/www;
        autoindex on;
        allowed_methods GET;
    }
}
}
