http {
server {
    listen 8080;
    root /Users/macbookuser/Desktop/NetCore/configs/autoindex/www;

    location / {
        root /Users/macbookuser/Desktop/NetCore/configs/autoindex/www;
        autoindex on;
        allowed_methods GET;
    }
}
}
