http {
server {
    listen 8080;
    root /Users/macbookuser/Desktop/NetCore/configs/multi/site1;

    location / {
        root /Users/macbookuser/Desktop/NetCore/configs/multi/site1;
        index index.html;
        allowed_methods GET;
    }
}

server {
    listen 8081;
    root /Users/macbookuser/Desktop/NetCore/configs/multi/site2;

    location / {
        root /Users/macbookuser/Desktop/NetCore/configs/multi/site2;
        index index.html;
        allowed_methods GET;
    }
}
}
