http {
server {
    listen 8080;
    root /Users/macbookuser/Desktop/NetCore/configs/allowed_methods/www;

    location / {
        root /Users/macbookuser/Desktop/NetCore/configs/allowed_methods/www;
        index index.html;
        allowed_methods GET;
    }

    location /upload {
        root /Users/macbookuser/Desktop/NetCore/configs/allowed_methods/www;
        allowed_methods POST;
        upload_location /Users/macbookuser/Desktop/NetCore/configs/allowed_methods/uploads;
    }
}
}
