http {
server {
    listen 8080;
    root /Users/macbookuser/Desktop/NetCore/configs/errors/www;

    location / {
        root /Users/macbookuser/Desktop/NetCore/configs/errors/www;
        index index.html;
        allowed_methods GET;
    }

    location /post-no-store {
        root /Users/macbookuser/Desktop/NetCore/configs/errors/www;
        allowed_methods POST;
    }

    location /noindex {
        root /Users/macbookuser/Desktop/NetCore/configs/errors/www;
        autoindex off;
        allowed_methods GET;
    }
}
}
