server {
    listen 8080;
    root /home/lenovo/Desktop/Webserv/www;
    client_max_body_size 1m;

    location / {
        root /home/lenovo/Desktop/Webserv/www;
        index index.html;
        allowed_methods GET;
    }

    location /cgi-bin {
        root /home/lenovo/Desktop/Webserv/www;
        allowed_methods GET POST;
        cgi_extension .py /usr/bin/python3;
        cgi_extension .php /usr/bin/php;
    }

    location /files {
        root /home/lenovo/Desktop/Webserv/www;
        autoindex on;
        allowed_methods GET DELETE;
    }

    location /upload {
        root /home/lenovo/Desktop/Webserv/www;
        allowed_methods POST;
        upload_location /home/lenovo/Desktop/Webserv/www/uploads;
    }
}
