server {
    listen 8080;
    root /Users/macbookuser/Desktop/NetCore/www;
    client_max_body_size 1m;

    location / {
        root /Users/macbookuser/Desktop/NetCore/www;
        index index.html;
        allowed_methods GET;
    }

    location /cgi-bin {
        root /Users/macbookuser/Desktop/NetCore/www;
        allowed_methods GET POST;
        cgi_extension .py /usr/bin/python3;
        cgi_extension .php /usr/bin/php-cgi;
    }

    location /files {
        root /Users/macbookuser/Desktop/NetCore/www;
        autoindex on;
        allowed_methods GET DELETE;
    }

    location /upload {
        root /Users/macbookuser/Desktop/NetCore/www;
        allowed_methods POST;
        upload_location /Users/macbookuser/Desktop/NetCore/www/uploads;
    }
}
