http {
server {
    listen 8080;
    root /home/lenovo/Desktop/Webserv/configs/return/www;

    location / {
        root /home/lenovo/Desktop/Webserv/configs/return/www;
        index index.html;
        allowed_methods GET;
    }

    location /old {
        return 301 http://localhost:8080/new/;
    }

    location /new {
        root /home/lenovo/Desktop/Webserv/configs/return/www;
        index index.html;
        allowed_methods GET;
    }
}
}
