http {
server {
    listen 8080;
    root /home/lenovo/Desktop/Webserv/configs/upload/www;
    client_max_body_size 10m;

    location / {
        root /home/lenovo/Desktop/Webserv/configs/upload/www;
        index index.html;
        allowed_methods GET;
    }

    location /upload {
        root /home/lenovo/Desktop/Webserv/configs/upload/www;
        allowed_methods POST;
        upload_location /home/lenovo/Desktop/Webserv/configs/upload/uploads/files;
    }

    location /files {
        root /home/lenovo/Desktop/Webserv/configs/upload/uploads;
        autoindex on;
        allowed_methods GET DELETE;
    }
}
}
