http {
server {
    listen 8080;
    root /home/saslanya/Desktop/NetCore/configs/default/www;

    location / {
        root /home/saslanya/Desktop/NetCore/configs/default/www;
        index index.html;
        allowed_methods GET POST DELETE;
    }
}
}
