http {
server {
    listen 8080;
    root /home/lenovo/Desktop/Webserv/configs/nested_locations/www;

    location / {
        root /home/lenovo/Desktop/Webserv/configs/nested_locations/www;
        index index.html;
        allowed_methods GET;
    }

    location /images {
        root /home/lenovo/Desktop/Webserv/configs/nested_locations/www;
        autoindex on;
        allowed_methods GET;
    }
}
}
