http {
server {
    listen 8080;
    root /Users/macbookuser/Desktop/NetCore/configs/nested_locations/www;

    location / {
        root /Users/macbookuser/Desktop/NetCore/configs/nested_locations/www;
        index index.html;
        allowed_methods GET;
    }

    location /images {
        root /Users/macbookuser/Desktop/NetCore/configs/nested_locations/www;
        autoindex on;
        allowed_methods GET;
    }
}
}
