server {
    listen 8081;
    root /home/mika/Desktop/NetCore/configs/tester/YoupiBanane;

    location / {
        allowed_methods GET;
        autoindex off;
    }

    location /cgi {
        allowed_methods POST;
        cgi_extension .bla /home/mika/Desktop/NetCore/configs/tester/cgi_tester;
    }

    location /post_body {
        allowed_methods POST;
        client_max_body_size 10000000000;
        root /home/mika/Desktop/NetCore/configs/tester/nonexistent;
    }

}
