name: Lexical CI

on:
  push:
    branches: [ "lexical_part" ]
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update packages and install compiler
        run: sudo apt update && sudo apt install -y build-essential make

      - name: Build tests
        run: make -f Makefile
        working-directory: test/lexical

      - name: Diagnostics
        run: |
          pwd
          ls -la
        working-directory: test/lexical

      - name: Run tests and save log
        run: ./test > lexical_test.log 2>&1
        working-directory: test/lexical

      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: lexical_test_log
          path: test/lexical/lexical_test.log

